// solid/src/App.jsx
import { createSignal, onMount } from 'solid-js'

function App() {
  const [todos, setTodos] = createSignal([])
  let todoText;

  onMount(() => {
    const existingTodos = localStorage.getItem('todos')
    setTodos(existingTodos ? JSON.parse(existingTodos) : [])
  })

  function addTodo(event) {
    event.preventDefault()
    const next = [...todos(), todoText.value]
    setTodos(next)
    localStorage.setItem('todos', JSON.stringify(next))
    todoText.value = ''
  }

  return (
    <div>
      <ul>
        {todos().map(todo => (<li key={Math.random()}>{todo}</li>))}
      </ul>

      <form onSubmit={addTodo}>
        <input type="text" ref={todoText} />
        <input type="submit" value="Add todo" />
      </form>
    </div>
  )
}

export default App

// 4-svelte/src/App.svelte
<script>
import { onMount } from "svelte";

let todos = []
let todoText = ''

onMount(() => {
	const existingTodos = JSON.parse(localStorage.getItem("todos"))
	todos = existingTodos || []
})

function addTodo() {
	todos = [todoText, ...todos]
	localStorage.setItem("todos", JSON.stringify(todos))
	todoText = ''
}
</script>

<main>
	<ul>
		{#each todos as todo}
			<li>{todo}</li>
		{/each}
	</ul>

	<form on:submit|preventDefault={addTodo}>
		<input bind:value={todoText} />
		<input type="submit" value="Add todo" />
	</form>
</main>

<style></style>
