// 4-svelte/src/App.svelte
<script>
import { onMount } from "svelte";

let todos = []
let todoText = ''

onMount(() => {
	const existingTodos = JSON.parse(localStorage.getItem("todos"))
	todos = existingTodos || []
})

function addTodo() {
	todos = [todoText, ...todos]
	localStorage.setItem("todos", JSON.stringify(todos))
	todoText = ''
}
</script>

<main>
	<ul>
		{#each todos as todo}
			<li>{todo}</li>
		{/each}
	</ul>

	<form on:submit|preventDefault={addTodo}>
		<input bind:value={todoText} />
		<input type="submit" value="Add todo" />
	</form>
</main>

<style></style>

// 2-angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {

  todos: string[] = [];
  todoText = '';

  ngOnInit() {
    const existingTodos = localStorage.getItem('todos');
    this.todos = JSON.parse(existingTodos as string) || [];
  }

  addTodo() {
    this.todos.push(this.todoText);
    localStorage.setItem('todos', JSON.stringify(this.todos));
  }

}

<ul>
  <li *ngFor="let todo of todos">{{todo}}</li>
</ul>

<form #mainForm="ngForm" (ngSubmit)="addTodo(); mainForm.resetForm()">
  <input name="todoText" [(ngModel)]="todoText">
  <input type="submit" value="Add Todo" />
</form>
