// solid/src/App.jsx
import { createSignal, onMount } from 'solid-js'

function App() {
  const [todos, setTodos] = createSignal([])
  let todoText;

  onMount(() => {
    const existingTodos = localStorage.getItem('todos')
    setTodos(existingTodos ? JSON.parse(existingTodos) : [])
  })

  function addTodo(event) {
    event.preventDefault()
    const next = [...todos(), todoText.value]
    setTodos(next)
    localStorage.setItem('todos', JSON.stringify(next))
    todoText.value = ''
  }

  return (
    <div>
      <ul>
        {todos().map(todo => (<li key={Math.random()}>{todo}</li>))}
      </ul>

      <form onSubmit={addTodo}>
        <input type="text" ref={todoText} />
        <input type="submit" value="Add todo" />
      </form>
    </div>
  )
}

export default App

// 1-react/src/App.js
import { useState, useEffect, useRef } from 'react'

function App() {
  const todoText = useRef()
  const [todos, setTodos] = useState(['hello'])

  function handleTodos(e) {
    e.preventDefault()
    const current = [todoText.current.value, ...todos]
    setTodos(current)
    localStorage.setItem('todos', JSON.stringify(current))
    todoText.current.value = ''
  }

  useEffect(() => {
    const existing = JSON.parse(localStorage.getItem('todos'))
    setTodos(existing ? existing : [])
  }, [])

  return (
    <div>
      <ul id="todos">{todos.map(todo => (
          <li key={Math.random()}>{todo}</li>
        )
      )}</ul>

      <form onSubmit={(e) => handleTodos(e)}>
        <input ref={todoText} />
        <input type="submit" value="Add Todo" />
      </form>
    </div>
  )
}

export default App
